# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings 
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tugberk Erol
name: Tugberk Erol
position: AI Researcher
email: tugberkerol1@gmail.com
description: |
  I am a PhD candidate in Computer Engineering at Gazi University, exploring the frontiers of medical image segmentation and self-distillation. My work focuses on improving model performance and uncertainty estimation in clinical applications.
  I am passionate about pushing deep learning for healthcare further, developing methods that make AI-assisted diagnosis more reliable and accurate.
  My current research interests include knowledge distillation and advanced segmentation techniques for medical imaging.

baseurl: "" # the subpath of your site, e.g. /blog

github_username: TugberkErol
google_scholar: https://scholar.google.com/citations?user=mWXIqF8AAAAJ&hl=tr&oi=ao


# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
